// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Taekwondo.Data;
using Taekwondo.Data.Entities;
using Taekwondo.Data.Enums;

namespace Taekwondo.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20180503033906_InitModel2018050301")]
    partial class InitModel2018050301
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Taekwondo.Data.Entities.AppEdition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Edition");

                    b.Property<bool>("IsMandatory");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Os");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.ToTable("AppEditions");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.Genearch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<int>("Gender");

                    b.Property<string>("GenearchName");

                    b.Property<string>("IdCardNo");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Mobile");

                    b.HasKey("Id");

                    b.ToTable("Genearches");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.GenearchChild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Appellation");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<int>("Dan");

                    b.Property<string>("GenearchChildName");

                    b.Property<long>("GenearchId");

                    b.Property<string>("IdCardNo");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("GenearchChildren");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.GenearchChildMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Appellation");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChildId");

                    b.Property<long>("GenearchId");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("GenearchChildMaps");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Application");

                    b.Property<string>("Callsite");

                    b.Property<string>("Exception");

                    b.Property<string>("Level");

                    b.Property<DateTime>("Logged");

                    b.Property<string>("Logger");

                    b.Property<string>("Message");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime>("ExpiredAt");

                    b.Property<string>("Ip");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Token");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("IconUrl");

                    b.Property<string>("Label");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long?>("MenuId");

                    b.Property<string>("ParentId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.Notice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<bool>("IsRead");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Message");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.SmsLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Ip");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Message");

                    b.Property<string>("Mobile");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.SystemSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("BusinessHoursFromAt");

                    b.Property<DateTime?>("BusinessHoursToAt");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("OpeningDay");

                    b.Property<string>("Pictures");

                    b.Property<string>("Summary");

                    b.Property<long>("TrainingOrganizationEntId");

                    b.Property<long>("TrainingOrganizationManagerUserId");

                    b.Property<string>("TrainingOrganizationName");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizations");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("ClassName");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<int>("Dan");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("TrainingOrganizationId");

                    b.Property<long>("TrainingOrganizationManageUserId");

                    b.Property<long>("TrainingOrganizationTeacherId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClasses");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassHomework", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Files");

                    b.Property<string>("Images");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Summary");

                    b.Property<string>("Title");

                    b.Property<long>("TrainingOrganizationClassId");

                    b.Property<long>("TrainingOrganizationClassTeacherId");

                    b.Property<long>("TrainingOrganizationId");

                    b.Property<long>("TrainingOrganizationManageUserId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassHomeworks");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassHomeworkAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Files");

                    b.Property<long>("GenearchChildId");

                    b.Property<string>("GenearchChildName");

                    b.Property<long>("GenearchId");

                    b.Property<string>("Images");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("ReadoverText");

                    b.Property<bool>("Readovered");

                    b.Property<int>("Stars");

                    b.Property<string>("Summary");

                    b.Property<long>("TrainingOrganizationClassHomeworkId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassHomeworkAnswers");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassHomeworkMarking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChildId");

                    b.Property<long>("GenearchId");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("TeacherId");

                    b.Property<long>("TrainingOrganizationClassHomeworkId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassHomeworkMarkings");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassLesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("LessonName");

                    b.Property<DateTime>("StartTime");

                    b.Property<long>("TrainingOrganizationClassId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassLessons");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChildId");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("TrainingOrganizationClassId");

                    b.Property<int>("TrainingOrganizationClassStudentStatus");

                    b.Property<long>("TrainingOrganizationId");

                    b.Property<long>("TrainingOrganizationManageUserId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassStudents");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassStudentLessonLeave", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<long?>("AuditorId");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChildId");

                    b.Property<bool>("IsAgreed");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Reason");

                    b.Property<long>("StudentLessonMapId");

                    b.Property<long>("TrainingOrganizationClassLessonId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassStudentLessonLeaves");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassStudentLessonMakeUp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChildId");

                    b.Property<long>("GenearchId");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("OriginalStudentLessonMapId");

                    b.Property<string>("Remark");

                    b.Property<int>("Status");

                    b.Property<long>("StudentLessonMapId");

                    b.Property<long>("TrainingOrganizationClassLessonId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassStudentLessonMakeUps");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassStudentLessonMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChildId");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("TrainingOrganizationClassLessonId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassStudentLessonMaps");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassStudentLessonSign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("GenearchChild");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("StudentLessonMapId");

                    b.Property<long>("TrainingOrganizationClassLessonId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassStudentLessonSigns");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationClassTeacherMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<int>("TeacherInClassType");

                    b.Property<long>("TrainingOrganizationClassId");

                    b.Property<long>("TrainingOrganizationTeacherId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationClassTeacherMaps");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationEnt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("ManagerId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationEnts");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationPrize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<int>("Integral");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Summary");

                    b.Property<long>("TrainingOrganizationId");

                    b.Property<string>("TrainingOrganizationPrizeName");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationPrizes");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationPrizeExchangeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("TrainingOrganizationPrizeId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationPrizeExchangeRecords");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<long>("TrainingOrganizationId");

                    b.Property<string>("TrainingOrganizationSubjectName");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationSubjects");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationTeacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Mobile");

                    b.Property<long>("TeacherId");

                    b.Property<string>("TeacherName");

                    b.Property<long>("TrainingOrganizationId");

                    b.Property<long>("TrainingOrganizationManageUserId");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationTeachers");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.TrainingOrganizationTeacherCurriculumVitae", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.HasKey("Id");

                    b.ToTable("TrainingOrganizationTeacherCurriculumVitaes");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("HeadPic");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password");

                    b.Property<int>("Status");

                    b.Property<string>("UserName");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.VerifyCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("next value for Ids");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime>("ExpriedAt");

                    b.Property<string>("Ip");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<string>("Mobile");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("VerifyCodes");
                });

            modelBuilder.Entity("Taekwondo.Data.Entities.Menu", b =>
                {
                    b.HasOne("Taekwondo.Data.Entities.Menu")
                        .WithMany("Children")
                        .HasForeignKey("MenuId");
                });
#pragma warning restore 612, 618
        }
    }
}
